spring:
  application:
    name: bab-deu-sil-bun

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  data:
    redis:
      port: 6379
      host: localhost

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true


jwt:
  secret-key: flsadjffsdnlfncnwqieynlcasoncbfjksabvjkdanjkcnasdiofnsadfnofsdlnqoiuyebnzc
  expire-ms: 3600000

refresh-token:
  expire-ms: 4000000

cloud:
  aws:
    credentials:
      accessKey: AKIAW3MEFXWOY7I5ZEKO
      secretKey: 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
    s3:
      bucketName: bab-deu-sil-bun
    region:
      static: ap-northeast-2
    stack:
      auto-: false