spring:

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  data:
    redis:
      port: 6379
      host: localhost

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true






jwt:
  secret-key: flsadjffsdnlfncnwqieynlcasoncbfjksabvjkdanjkcnasdiofnsadfnofsdlnqoiuyebnzc
  expire-ms: 3600000

refresh-token:
  expire-ms: 4000000