spring:

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  data:
    redis:
      host: redis-17192.c244.us-east-1-2.ec2.redns.redis-cloud.com
      port: 17192
      username: default
      password: AAp61mDXJemGKf1x6YYAHhisfzVJHHpx

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: joj931017@gmail.com
    password: vbsp hwzk wdkq rfxr
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true




jwt:
  secret-key: flsadjffsdnlfncnwqieynlcasoncbfjksabvjkdanjkcnasdiofnsadfnofsdlnqoiuyebnzc
  expire-ms: 3600000

refresh-token:
  expire-second: 4000000



#  cloud.aws.credentials.accessKey=AKIAW3MEFXWOY7I5ZEKO
#  cloud.aws.credentials.secretKey=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
#  cloud.aws.s3.bucketName=bab-deu-sil-bun
#  cloud.aws.region.static=ap-northeast-2
#  cloud.aws.stack.auto-=false
#
cloud:
  aws:
    credentials:
      accessKey: AKIAW3MEFXWOY7I5ZEKO
      secretKey: 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
    s3:
      bucketName: bab-deu-sil-bun
    region:
      static: ap-northeast-2
    stack:
      auto-: false


# 포트원
imp:
  code: imp51248204
  api:
    key: 4565002230026523
    secretKey: taA7UDXYAmbowyCPInAp6K1n1zSJKraWslG5mG7A49k4BtJ2zoT5g44C1FdGMwob90He2Uwe6p5Ebmn5

