### 사용자 회원가입
POST http://localhost:8080/api/users/signup
Content-Type: application/json

{
  "schoolId": 1,
  "majorId": 1,
  "email": "user@test.com",
  "password": "1234",
  "name": "usertest",
  "nickname": "testnick",
  "phoneNumber": "01011111111",
  "address": {
    "postal": "postal",
    "streetAddress": "street",
    "detailAddress": "detail"
  }
}

### 사업자 회원가입
POST http://localhost:8080/api/businesses/signup
Content-Type: application/json

{
"email": "business@test.com",
"password": "1234",
"name": "businesstest",
"phoneNumber": "01022222222",
"businessNumber": "12341234",
"address": {
"postal": "postal",
"streetAddress": "street",
"detailAddress": "detail"
}
}

### 사용자 로그인
POST localhost:8080/api/users/signin
Content-Type: application/json

{
  "email": "testuser@test.com",
  "password": "1234"
}

### 사업자 로그인
POST localhost:8080/api/signin
Content-Type: application/json

{
  "email": "business@test.com",
  "password": "1234"
}

### 로그아웃
POST localhost:8080/api/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IlJPTEVfVVNFUl90ZXN0dXNlckB0ZXN0LmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJleHAiOjE3MjM3ODg2MTJ9.0SE1svE3i6zLdzCtm_kVbBuTIZN2L6t9u1Nqo9WWC9s

### 리프레시 토큰 재발급
POST localhost:8080/api/refresh-token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IlJPTEVfVVNFUjp0ZXN0dXNlckB0ZXN0LmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJleHAiOjE3MjM4OTg5OTB9.UtRCkEJLrlIewHp_aitdIK24NdvwpCb1lt1VYeoDc-Q
Cookie: refresh_token=86a58b7b-124b-4df2-8087-c76bd57afca3

### 회원 탈퇴
POST localhost:8080/api/users/withdrawal
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3R1c2VyQHRlc3QuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcyMzExNTk2NH0.7OI6elEfnu40xbR0maZ66WNA4Pix4d_IvKG4qYengE8

{
  "password": "1234"
}